#define INPUT_ESCAPE     0x01
#define INPUT_1          0x02
#define INPUT_2          0x03
#define INPUT_3          0x04
#define INPUT_4          0x05
#define INPUT_5          0x06
#define INPUT_6          0x07
#define INPUT_7          0x08
#define INPUT_8          0x09
#define INPUT_9          0x0a
#define INPUT_0          0x0b
#define INPUT_MINUS      0x0c
#define INPUT_EQUALS     0x0d
#define INPUT_BACK       0x0e
#define INPUT_TAB        0x0f
#define INPUT_Q          0x10
#define INPUT_W          0x11
#define INPUT_E          0x12
#define INPUT_R          0x13
#define INPUT_T          0x14
#define INPUT_Y          0x15
#define INPUT_U          0x16
#define INPUT_I          0x17
#define INPUT_O          0x18
#define INPUT_P          0x19
#define INPUT_LBRACKET   0x1a
#define INPUT_RBRACKET   0x1b
#define INPUT_RETURN     0x1c
#define INPUT_LCON       0x1d
#define INPUT_A          0x1e
#define INPUT_S          0x1f
#define INPUT_D          0x20
#define INPUT_F          0x21
#define INPUT_G          0x22
#define INPUT_H          0x23
#define INPUT_J          0x24
#define INPUT_K          0x25
#define INPUT_L          0x26
#define INPUT_SEMICOLON  0x27
#define INPUT_APOSTROPHE 0x28
#define INPUT_GRAVE      0x29
#define INPUT_LSHIFT     0x2a
#define INPUT_BACKSLASH  0x2b
#define INPUT_Z          0x2c
#define INPUT_X          0x2d
#define INPUT_C          0x2e
#define INPUT_V          0x2f
#define INPUT_B          0x30
#define INPUT_N          0x31
#define INPUT_M          0x32
#define INPUT_COMMA      0x33
#define INPUT_PERIOD     0x34
#define INPUT_SLASH      0x35
#define INPUT_RSHIFT     0x36
#define INPUT_MULTIPLY   0x37
#define INPUT_LMENU      0x38
#define INPUT_SPACE      0x39
#define INPUT_CAPITAL    0x3a
#define INPUT_F1         0x3b
#define INPUT_F2         0x3c
#define INPUT_F3         0x3d
#define INPUT_F4         0x3e
#define INPUT_F5         0x3f
#define INPUT_F6         0x40
#define INPUT_F7         0x41
#define INPUT_F8         0x42
#define INPUT_F9         0x43
#define INPUT_F10        0x44
#define INPUT_NUMLOCK    0x45
#define INPUT_SCROLL     0x46
#define INPUT_NUM7       0x47
#define INPUT_NUM8       0x48
#define INPUT_NUM9       0x49
#define INPUT_SUBTRACT   0x4a
#define INPUT_NUM4       0x4b
#define INPUT_NUM5       0x4c
#define INPUT_NUM6       0x4d
#define INPUT_ADD        0x4e
#define INPUT_NUM1       0x4f
#define INPUT_NUM2       0x50
#define INPUT_NUM3       0x51
#define INPUT_NUM0       0x52
#define INPUT_DECIMAL    0x53
#define INPUT_F11        0x57
#define INPUT_F12        0x58
#define INPUT_KANA       0x70
#define INPUT_CONVERT    0x79
#define INPUT_NOCONVERT  0x7b
#define INPUT_YEN        0x7d
#define INPUT_CIRCUMFLEX 0x90
#define INPUT_COLON      0x92
#define INPUT_KANJI      0x94
#define INPUT_NUMENTER   0x9c
#define INPUT_RCON       0x9d
#define INPUT_DIVIDE     0xb5
#define INPUT_SYSRQ      0xb7
#define INPUT_RMENU      0xb8
#define INPUT_PAUSE      0xc5
#define INPUT_HOME       0xc7
#define INPUT_UP         0xc8
#define INPUT_PRIOR      0xc9
#define INPUT_LEFT       0xcb
#define INPUT_RIGHT      0xcd
#define INPUT_END        0xcf
#define INPUT_DOWN       0xd0
#define INPUT_NEXT       0xd1
#define INPUT_INSERT     0xd2
#define INPUT_DELETE     0xd3
#define INPUT_LWIN       0xdb
#define INPUT_RWIN       0xdc
#define INPUT_APPS       0xdd
#define INPUT_POWER      0xde
#define INPUT_SLEEP      0xdf