#pragma once

#define INPUT_LBUTTON  0x01
#define INPUT_RBUTTON  0x02
#define INPUT_CANCEL   0x03
#define INPUT_CBUTTON  0x04
#define INPUT_XBUTTON1 0x05
#define INPUT_XBUTTON2 0x06
#define INPUT_BACK     0x08
#define INPUT_TAB      0x09
#define INPUT_CLEAR    0x0c
#define INPUT_RETURN   0x0d
#define INPUT_SHIFT    0x10
#define INPUT_CTRL     0x11
#define INPUT_MENU     0x12
#define INPUT_PAUSE    0x13
#define INPUT_CAPS     0x14
#define INPUT_KANA     0x15
#define INPUT_JUNJA    0x17
#define INPUT_FINAL    0x18
#define INPUT_KANJI    0x19
#define INPUT_ESCAPE   0x1b
#define INPUT_CONVERT  0x1c
#define INPUT_NONCNV   0x1d
#define INPUT_ACCEPT   0x1e
#define INPUT_MODE     0x1f
#define INPUT_SPACE    0x20
#define INPUT_PAGEUP   0x21
#define INPUT_PAGEDOWN 0x22
#define INPUT_END      0x23
#define INPUT_HOME     0x24
#define INPUT_LEFT     0x25
#define INPUT_UP       0x26
#define INPUT_RIGHT    0x27
#define INPUT_DOWN     0x28
#define INPUT_SELECT   0x29
#define INPUT_PRINT    0x2a
#define INPUT_EXCUTE   0x2b
#define INPUT_PRINTSC  0x2c
#define INPUT_INSERT   0x2d
#define INPUT_DELETE   0x2e
#define INPUT_HELP     0x2f
#define INPUT_0        0x30
#define INPUT_1        0x31
#define INPUT_2        0x32
#define INPUT_3        0x33
#define INPUT_4        0x34
#define INPUT_5        0x35
#define INPUT_6        0x36
#define INPUT_7        0x37
#define INPUT_8        0x38
#define INPUT_9        0x39
#define INPUT_A        'A'
#define INPUT_B        'B'
#define INPUT_C        'C'
#define INPUT_D        'D'
#define INPUT_E        'E'
#define INPUT_F        'F'
#define INPUT_G        'G'
#define INPUT_H        'H'
#define INPUT_I        'I'
#define INPUT_J        'J'
#define INPUT_K        'K'
#define INPUT_L        'L'
#define INPUT_M        'M'
#define INPUT_N        'N'
#define INPUT_O        'O'
#define INPUT_P        'P'
#define INPUT_Q        'Q'
#define INPUT_R        'R'
#define INPUT_S        'S'
#define INPUT_T        'T'
#define INPUT_U        'U'
#define INPUT_V        'V'
#define INPUT_W        'W'
#define INPUT_X        'X'
#define INPUT_Y        'Y'
#define INPUT_Z        'Z'
#define INPUT_LWIN     0x5b
#define INPUT_RWIN     0x5c
#define INPUT_APPS     0x5d
#define INPUT_SLEEP    0x5f
#define INPUT_NUM0     0x60
#define INPUT_NUM1     0x61
#define INPUT_NUM2     0x62
#define INPUT_NUM3     0x63
#define INPUT_NUM4     0x64
#define INPUT_NUM5     0x65
#define INPUT_NUM6     0x66
#define INPUT_NUM7     0x67
#define INPUT_NUM8     0x68
#define INPUT_NUM9     0x69
#define INPUT_MULTI    0x6a
#define INPUT_ADD      0x6b
#define INPUT_SEPARAT  0x6c
#define INPUT_SUB      0x6d
#define INPUT_DECIMAL  0x6e
#define INPUT_DIVIDE   0x6f
#define INPUT_F1       0x70
#define INPUT_F2       0x71
#define INPUT_F3       0x72
#define INPUT_F4       0x73
#define INPUT_F5       0x74
#define INPUT_F6       0x75
#define INPUT_F7       0x76
#define INPUT_F8       0x77
#define INPUT_F9       0x78
#define INPUT_F10      0x79
#define INPUT_F11      0x7a
#define INPUT_F12      0x7b
#define INPUT_F13      0x7c
#define INPUT_F14      0x7d
#define INPUT_F15      0x7e
#define INPUT_F16      0x7f
#define INPUT_F17      0x80
#define INPUT_F18      0x81
#define INPUT_F19      0x82
#define INPUT_F20      0x83
#define INPUT_F21      0x84
#define INPUT_F22      0x85
#define INPUT_F23      0x86
#define INPUT_F24      0x87
#define INPUT_NUMLOCK  0x90
#define INPUT_SCROLL   0x91
#define INPUT_LSHIFT   0xa0
#define INPUT_RSHIFT   0xa1
#define INPUT_LCTRL    0xa2
#define INPUT_RCTRL    0xa3
#define INPUT_LALT     0xa4
#define INPUT_RALT     0xa5
#define INPUT_MUTE     0xad
#define INPUT_VOLDOWN  0xae
#define INPUT_VOLUP    0xaf
#define INPUT_NEXTRACK 0xb0
#define INPUT_PRETRACK 0xb1
#define INPUT_STOP     0xb2
#define INPUT_PLAY     0xb3
#define INPUT_ASTERISK 0xba
#define INPUT_PLUS     0xbb
#define INPUT_COMMA    0xbc
#define INPUT_MINUS    0xbd
#define INPUT_PERIOD   0xbe
#define INPUT_SLASH    0xbf
#define INPUT_AT       0xc0
#define INPUT_LBRACKET 0xdb
#define INPUT_EN       0xdc
#define INPUT_RBRACKET 0xdd
#define INPUT_TILDE    0xde
